language: ruby
rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx
  # - ruby-head  # seems unstable on travis at this time
addons:
  code_climate:
    repo_token: d414084f17a07a6b2d7da72eaa35d92281554a4266ab8d6246fee1f6c0c161b6
